package com.codekeys.ime;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * EmojiData — categorized, searchable emoji set bundled with the app.
 *
 * <p>We avoid pulling in an external library by shipping a curated set of the
 * most commonly used emoji characters along with short, lowercase keyword
 * tokens used for the in-keyboard search box. Each category is a stable,
 * insertion-ordered list so the UI tabs always render in the same order as the
 * standard Unicode CLDR groupings.
 *
 * <p>Search is intentionally tolerant: any keyword that <em>contains</em> the
 * query string matches, so "smil" matches "smile", "smiling", etc. Keywords
 * are space-separated within each emoji's metadata string.
 */
final class EmojiData {

    private EmojiData() {}

    /** Friendly display labels for category tabs (in render order). */
    static final String[] CATEGORY_NAMES = {
        "Recent", "😀", "🐻", "🍔", "⚽", "✈️", "💡", "❤", "🚩"
    };

    /** Stable category keys used for prefs storage of the "recent" list. */
    static final String[] CATEGORY_KEYS = {
        "recent", "smileys", "animals", "food", "activities", "travel",
        "objects", "symbols", "flags"
    };

    /**
     * Returns the emoji list for the given category key (one of
     * {@link #CATEGORY_KEYS}). Never returns {@code null}; an unknown key
     * yields an empty list.
     */
    static List<String> emojisFor(String categoryKey) {
        List<Entry> list = BY_CATEGORY.get(categoryKey);
        if (list == null) return Collections.emptyList();
        ArrayList<String> out = new ArrayList<>(list.size());
        for (Entry e : list) out.add(e.emoji);
        return out;
    }

    /**
     * Search across every category. The query is lower-cased and trimmed; an
     * emoji matches when any of its keywords contains the query token.
     * Results preserve category order then within-category order so the user
     * sees a stable list across taps.
     */
    static List<String> search(String query) {
        if (query == null) return Collections.emptyList();
        String q = query.trim().toLowerCase();
        if (q.isEmpty()) return Collections.emptyList();

        ArrayList<String> out = new ArrayList<>();
        for (Map.Entry<String, List<Entry>> cat : BY_CATEGORY.entrySet()) {
            if ("recent".equals(cat.getKey())) continue; // recent is dynamic
            for (Entry e : cat.getValue()) {
                if (e.matches(q) && !out.contains(e.emoji)) out.add(e.emoji);
            }
        }
        return out;
    }

    // ─── Internal data ────────────────────────────────────────────────────────

    private static final class Entry {
        final String emoji;
        final String keywords; // space-separated lowercase tokens
        Entry(String emoji, String keywords) {
            this.emoji = emoji;
            this.keywords = keywords;
        }
        boolean matches(String q) { return keywords.contains(q); }
    }

    /** Insertion-ordered so {@link #CATEGORY_KEYS} stays in sync. */
    private static final Map<String, List<Entry>> BY_CATEGORY = new LinkedHashMap<>();
    static {
        // "recent" is filled at runtime from prefs; start empty.
        BY_CATEGORY.put("recent", new ArrayList<>());

        BY_CATEGORY.put("smileys", Arrays.asList(
            new Entry("😀", "grinning happy smile face"),
            new Entry("😃", "grinning open smile happy face"),
            new Entry("😄", "smile happy laugh"),
            new Entry("😁", "beaming grin smile"),
            new Entry("😆", "laugh grin"),
            new Entry("😅", "sweat smile relief"),
            new Entry("🤣", "rofl laugh rolling"),
            new Entry("😂", "joy tears laugh cry"),
            new Entry("🙂", "slight smile"),
            new Entry("🙃", "upside down silly"),
            new Entry("😉", "wink flirt"),
            new Entry("😊", "blush smile happy"),
            new Entry("😇", "innocent angel halo"),
            new Entry("🥰", "love smile hearts"),
            new Entry("😍", "love heart eyes"),
            new Entry("🤩", "star eyes excited"),
            new Entry("😘", "kiss heart blow"),
            new Entry("😗", "kiss"),
            new Entry("😚", "kiss closed eyes"),
            new Entry("😙", "kiss smile"),
            new Entry("🥲", "smile tear"),
            new Entry("😋", "yum tasty tongue"),
            new Entry("😛", "tongue stuck"),
            new Entry("😜", "wink tongue"),
            new Entry("🤪", "zany silly crazy"),
            new Entry("😝", "tongue squint"),
            new Entry("🤑", "money mouth dollar"),
            new Entry("🤗", "hug hugging"),
            new Entry("🤭", "hand mouth oops"),
            new Entry("🤫", "shush quiet"),
            new Entry("🤔", "thinking think"),
            new Entry("🤐", "zip mouth quiet"),
            new Entry("🤨", "raised brow suspicious"),
            new Entry("😐", "neutral meh"),
            new Entry("😑", "expressionless blank"),
            new Entry("😶", "no mouth speechless"),
            new Entry("😏", "smirk"),
            new Entry("😒", "unamused meh"),
            new Entry("🙄", "eye roll"),
            new Entry("😬", "grimace awkward"),
            new Entry("😌", "relieved calm"),
            new Entry("😔", "pensive sad"),
            new Entry("😪", "sleepy tired"),
            new Entry("😴", "sleep zzz"),
            new Entry("😷", "mask sick"),
            new Entry("🤒", "thermometer sick"),
            new Entry("🤕", "head bandage hurt"),
            new Entry("🤢", "nauseated sick"),
            new Entry("🤮", "vomit sick"),
            new Entry("🤧", "sneeze sick"),
            new Entry("🥵", "hot heat sweat"),
            new Entry("🥶", "cold freeze"),
            new Entry("🥴", "woozy dizzy"),
            new Entry("😵", "dizzy knocked"),
            new Entry("🤯", "exploding mind blown"),
            new Entry("🤠", "cowboy hat"),
            new Entry("🥳", "party celebrate"),
            new Entry("😎", "cool sunglasses"),
            new Entry("🤓", "nerd glasses"),
            new Entry("🧐", "monocle inspect"),
            new Entry("😕", "confused"),
            new Entry("😟", "worried"),
            new Entry("🙁", "frown sad"),
            new Entry("☹", "frown sad"),
            new Entry("😮", "open mouth surprised"),
            new Entry("😯", "hushed surprised"),
            new Entry("😲", "astonished shocked"),
            new Entry("😳", "flushed embarrassed"),
            new Entry("🥺", "pleading begging"),
            new Entry("😦", "frown open"),
            new Entry("😧", "anguished"),
            new Entry("😨", "fearful afraid"),
            new Entry("😰", "anxious sweat"),
            new Entry("😥", "sad relief"),
            new Entry("😢", "cry tear sad"),
            new Entry("😭", "sob crying loud"),
            new Entry("😱", "scream shocked scared"),
            new Entry("😖", "confounded"),
            new Entry("😣", "persevere"),
            new Entry("😞", "disappointed sad"),
            new Entry("😓", "sweat sad"),
            new Entry("😩", "weary tired"),
            new Entry("😫", "tired exhausted"),
            new Entry("🥱", "yawn tired"),
            new Entry("😤", "huff angry steam"),
            new Entry("😡", "angry mad rage"),
            new Entry("😠", "angry mad"),
            new Entry("🤬", "swearing curse mad"),
            new Entry("😈", "smiling devil"),
            new Entry("👿", "angry devil"),
            new Entry("💀", "skull dead"),
            new Entry("☠", "skull crossbones"),
            new Entry("💩", "poo poop"),
            new Entry("🤡", "clown"),
            new Entry("👹", "ogre"),
            new Entry("👺", "goblin"),
            new Entry("👻", "ghost spooky"),
            new Entry("👽", "alien"),
            new Entry("👾", "alien monster"),
            new Entry("🤖", "robot"),
            new Entry("👍", "thumbs up like"),
            new Entry("👎", "thumbs down dislike"),
            new Entry("👏", "clap applause"),
            new Entry("🙌", "raised hands praise"),
            new Entry("👐", "open hands"),
            new Entry("🤝", "handshake deal"),
            new Entry("🙏", "pray thanks please"),
            new Entry("✌", "peace victory"),
            new Entry("🤞", "fingers crossed luck"),
            new Entry("🤟", "love you sign"),
            new Entry("🤘", "rock metal"),
            new Entry("👌", "ok perfect"),
            new Entry("👈", "point left"),
            new Entry("👉", "point right"),
            new Entry("👆", "point up"),
            new Entry("👇", "point down"),
            new Entry("☝", "index finger up"),
            new Entry("✋", "stop hand"),
            new Entry("🤚", "raised back hand"),
            new Entry("🖐", "splayed hand"),
            new Entry("🖖", "vulcan spock"),
            new Entry("👋", "wave hi hello"),
            new Entry("💪", "muscle strong flex"),
            new Entry("🤳", "selfie"),
            new Entry("✍", "writing pen"),
            new Entry("🧠", "brain"),
            new Entry("👀", "eyes look"),
            new Entry("👁", "eye"),
            new Entry("👅", "tongue"),
            new Entry("👄", "lips mouth")
        ));

        BY_CATEGORY.put("animals", Arrays.asList(
            new Entry("🐶", "dog puppy face"),
            new Entry("🐱", "cat kitten face"),
            new Entry("🐭", "mouse"),
            new Entry("🐹", "hamster"),
            new Entry("🐰", "rabbit bunny"),
            new Entry("🦊", "fox"),
            new Entry("🐻", "bear"),
            new Entry("🐼", "panda"),
            new Entry("🐨", "koala"),
            new Entry("🐯", "tiger"),
            new Entry("🦁", "lion"),
            new Entry("🐮", "cow"),
            new Entry("🐷", "pig"),
            new Entry("🐽", "pig nose"),
            new Entry("🐸", "frog"),
            new Entry("🐵", "monkey"),
            new Entry("🐔", "chicken hen"),
            new Entry("🐧", "penguin"),
            new Entry("🐦", "bird"),
            new Entry("🐤", "chick baby"),
            new Entry("🦆", "duck"),
            new Entry("🦅", "eagle"),
            new Entry("🦉", "owl"),
            new Entry("🦇", "bat"),
            new Entry("🐺", "wolf"),
            new Entry("🐗", "boar"),
            new Entry("🐴", "horse face"),
            new Entry("🦄", "unicorn"),
            new Entry("🐝", "bee"),
            new Entry("🪲", "beetle"),
            new Entry("🐛", "bug worm"),
            new Entry("🦋", "butterfly"),
            new Entry("🐌", "snail"),
            new Entry("🐞", "ladybug"),
            new Entry("🐜", "ant"),
            new Entry("🦟", "mosquito"),
            new Entry("🦗", "cricket"),
            new Entry("🕷", "spider"),
            new Entry("🦂", "scorpion"),
            new Entry("🐢", "turtle"),
            new Entry("🐍", "snake"),
            new Entry("🦎", "lizard"),
            new Entry("🦖", "trex dinosaur"),
            new Entry("🦕", "sauropod dinosaur"),
            new Entry("🐙", "octopus"),
            new Entry("🦑", "squid"),
            new Entry("🦐", "shrimp"),
            new Entry("🦞", "lobster"),
            new Entry("🦀", "crab"),
            new Entry("🐡", "blowfish"),
            new Entry("🐠", "tropical fish"),
            new Entry("🐟", "fish"),
            new Entry("🐬", "dolphin"),
            new Entry("🐳", "whale spout"),
            new Entry("🐋", "whale"),
            new Entry("🦈", "shark"),
            new Entry("🐊", "crocodile"),
            new Entry("🐅", "tiger animal"),
            new Entry("🐆", "leopard"),
            new Entry("🦓", "zebra"),
            new Entry("🦍", "gorilla"),
            new Entry("🐘", "elephant"),
            new Entry("🦏", "rhinoceros rhino"),
            new Entry("🐪", "camel"),
            new Entry("🐫", "two hump camel"),
            new Entry("🦒", "giraffe"),
            new Entry("🦘", "kangaroo"),
            new Entry("🐃", "buffalo"),
            new Entry("🐂", "ox"),
            new Entry("🐄", "cow animal"),
            new Entry("🐎", "horse"),
            new Entry("🐖", "pig animal"),
            new Entry("🐏", "ram"),
            new Entry("🐑", "sheep"),
            new Entry("🐐", "goat"),
            new Entry("🦌", "deer"),
            new Entry("🐕", "dog animal"),
            new Entry("🐩", "poodle"),
            new Entry("🦮", "guide dog"),
            new Entry("🐈", "cat animal"),
            new Entry("🐓", "rooster"),
            new Entry("🦃", "turkey"),
            new Entry("🦚", "peacock"),
            new Entry("🦜", "parrot"),
            new Entry("🐇", "rabbit animal"),
            new Entry("🐁", "mouse animal"),
            new Entry("🐀", "rat"),
            new Entry("🐿", "chipmunk squirrel"),
            new Entry("🦔", "hedgehog"),
            new Entry("🌸", "cherry blossom flower"),
            new Entry("🌹", "rose flower"),
            new Entry("🌻", "sunflower"),
            new Entry("🌷", "tulip"),
            new Entry("🌼", "blossom flower"),
            new Entry("🌺", "hibiscus"),
            new Entry("🌱", "seedling"),
            new Entry("🌲", "evergreen tree"),
            new Entry("🌳", "tree"),
            new Entry("🌴", "palm tree"),
            new Entry("🌵", "cactus"),
            new Entry("🍀", "four leaf clover luck"),
            new Entry("🍁", "maple leaf"),
            new Entry("🍂", "fallen leaf"),
            new Entry("🍃", "leaf wind")
        ));

        BY_CATEGORY.put("food", Arrays.asList(
            new Entry("🍏", "green apple"),
            new Entry("🍎", "apple red"),
            new Entry("🍐", "pear"),
            new Entry("🍊", "tangerine orange"),
            new Entry("🍋", "lemon"),
            new Entry("🍌", "banana"),
            new Entry("🍉", "watermelon"),
            new Entry("🍇", "grapes"),
            new Entry("🍓", "strawberry"),
            new Entry("🫐", "blueberries"),
            new Entry("🍈", "melon"),
            new Entry("🍒", "cherries"),
            new Entry("🍑", "peach"),
            new Entry("🥭", "mango"),
            new Entry("🍍", "pineapple"),
            new Entry("🥥", "coconut"),
            new Entry("🥝", "kiwi"),
            new Entry("🍅", "tomato"),
            new Entry("🍆", "eggplant"),
            new Entry("🥑", "avocado"),
            new Entry("🥦", "broccoli"),
            new Entry("🥬", "leafy green"),
            new Entry("🥒", "cucumber"),
            new Entry("🌶", "pepper hot"),
            new Entry("🌽", "corn"),
            new Entry("🥕", "carrot"),
            new Entry("🧄", "garlic"),
            new Entry("🧅", "onion"),
            new Entry("🥔", "potato"),
            new Entry("🍠", "sweet potato"),
            new Entry("🥐", "croissant"),
            new Entry("🥯", "bagel"),
            new Entry("🍞", "bread"),
            new Entry("🥖", "baguette"),
            new Entry("🥨", "pretzel"),
            new Entry("🧀", "cheese"),
            new Entry("🥚", "egg"),
            new Entry("🍳", "cooking egg fried"),
            new Entry("🧈", "butter"),
            new Entry("🥞", "pancakes"),
            new Entry("🧇", "waffle"),
            new Entry("🥓", "bacon"),
            new Entry("🥩", "steak meat"),
            new Entry("🍗", "drumstick chicken"),
            new Entry("🍖", "meat bone"),
            new Entry("🌭", "hotdog"),
            new Entry("🍔", "burger hamburger"),
            new Entry("🍟", "fries"),
            new Entry("🍕", "pizza"),
            new Entry("🥪", "sandwich"),
            new Entry("🌮", "taco"),
            new Entry("🌯", "burrito"),
            new Entry("🥙", "stuffed flatbread"),
            new Entry("🧆", "falafel"),
            new Entry("🥘", "shallow pan food"),
            new Entry("🍲", "pot of food stew"),
            new Entry("🥣", "bowl spoon"),
            new Entry("🥗", "salad"),
            new Entry("🍿", "popcorn"),
            new Entry("🧂", "salt"),
            new Entry("🥫", "canned food"),
            new Entry("🍱", "bento"),
            new Entry("🍘", "rice cracker"),
            new Entry("🍙", "rice ball"),
            new Entry("🍚", "rice"),
            new Entry("🍛", "curry"),
            new Entry("🍜", "ramen noodles"),
            new Entry("🍝", "spaghetti pasta"),
            new Entry("🍠", "yam"),
            new Entry("🍢", "oden"),
            new Entry("🍣", "sushi"),
            new Entry("🍤", "fried shrimp"),
            new Entry("🍥", "fish cake"),
            new Entry("🥮", "moon cake"),
            new Entry("🍡", "dango"),
            new Entry("🥟", "dumpling"),
            new Entry("🥠", "fortune cookie"),
            new Entry("🥡", "takeout"),
            new Entry("🍦", "soft serve ice cream"),
            new Entry("🍧", "shaved ice"),
            new Entry("🍨", "ice cream"),
            new Entry("🍩", "donut"),
            new Entry("🍪", "cookie"),
            new Entry("🎂", "birthday cake"),
            new Entry("🍰", "cake slice"),
            new Entry("🧁", "cupcake"),
            new Entry("🥧", "pie"),
            new Entry("🍫", "chocolate"),
            new Entry("🍬", "candy"),
            new Entry("🍭", "lollipop"),
            new Entry("🍮", "custard"),
            new Entry("🍯", "honey"),
            new Entry("🍼", "baby bottle milk"),
            new Entry("🥛", "milk glass"),
            new Entry("☕", "coffee hot drink"),
            new Entry("🍵", "tea"),
            new Entry("🍶", "sake"),
            new Entry("🍾", "champagne bottle"),
            new Entry("🍷", "wine glass"),
            new Entry("🍸", "cocktail"),
            new Entry("🍹", "tropical drink"),
            new Entry("🍺", "beer"),
            new Entry("🍻", "beers cheers"),
            new Entry("🥂", "clinking glasses"),
            new Entry("🥃", "tumbler whiskey"),
            new Entry("🥤", "cup straw soda"),
            new Entry("🧃", "juice box"),
            new Entry("🧉", "mate"),
            new Entry("🧊", "ice cube")
        ));

        BY_CATEGORY.put("activities", Arrays.asList(
            new Entry("⚽", "soccer football"),
            new Entry("🏀", "basketball"),
            new Entry("🏈", "american football"),
            new Entry("⚾", "baseball"),
            new Entry("🥎", "softball"),
            new Entry("🎾", "tennis"),
            new Entry("🏐", "volleyball"),
            new Entry("🏉", "rugby"),
            new Entry("🥏", "frisbee"),
            new Entry("🎱", "8 ball billiards"),
            new Entry("🏓", "ping pong"),
            new Entry("🏸", "badminton"),
            new Entry("🥅", "goal net"),
            new Entry("🏒", "hockey"),
            new Entry("🏑", "field hockey"),
            new Entry("🥍", "lacrosse"),
            new Entry("🏏", "cricket"),
            new Entry("⛳", "golf flag"),
            new Entry("🪁", "kite"),
            new Entry("🏹", "bow arrow"),
            new Entry("🎣", "fishing pole"),
            new Entry("🤿", "diving mask"),
            new Entry("🥊", "boxing glove"),
            new Entry("🥋", "martial arts"),
            new Entry("🎽", "running shirt"),
            new Entry("🛹", "skateboard"),
            new Entry("🛼", "roller skate"),
            new Entry("🛷", "sled"),
            new Entry("⛸", "ice skate"),
            new Entry("🥌", "curling stone"),
            new Entry("🎿", "skis"),
            new Entry("⛷", "skier"),
            new Entry("🏂", "snowboarder"),
            new Entry("🏆", "trophy winner"),
            new Entry("🥇", "gold medal first"),
            new Entry("🥈", "silver medal second"),
            new Entry("🥉", "bronze medal third"),
            new Entry("🎯", "target"),
            new Entry("🎳", "bowling"),
            new Entry("🎮", "video game"),
            new Entry("🎰", "slot machine"),
            new Entry("🎲", "dice"),
            new Entry("🧩", "puzzle"),
            new Entry("♟", "chess pawn"),
            new Entry("🃏", "joker card"),
            new Entry("🀄", "mahjong"),
            new Entry("🎴", "flower cards"),
            new Entry("🎭", "performing arts"),
            new Entry("🎨", "art palette"),
            new Entry("🎬", "clapper board film"),
            new Entry("🎤", "microphone"),
            new Entry("🎧", "headphone"),
            new Entry("🎼", "score music"),
            new Entry("🎹", "piano"),
            new Entry("🥁", "drum"),
            new Entry("🎷", "saxophone"),
            new Entry("🎺", "trumpet"),
            new Entry("🎸", "guitar"),
            new Entry("🪕", "banjo"),
            new Entry("🎻", "violin")
        ));

        BY_CATEGORY.put("travel", Arrays.asList(
            new Entry("🚗", "car red"),
            new Entry("🚕", "taxi"),
            new Entry("🚙", "suv"),
            new Entry("🚌", "bus"),
            new Entry("🚎", "trolleybus"),
            new Entry("🏎", "racing car"),
            new Entry("🚓", "police car"),
            new Entry("🚑", "ambulance"),
            new Entry("🚒", "fire engine"),
            new Entry("🚐", "minibus"),
            new Entry("🚚", "delivery truck"),
            new Entry("🚛", "lorry truck"),
            new Entry("🚜", "tractor"),
            new Entry("🛴", "scooter"),
            new Entry("🚲", "bicycle"),
            new Entry("🛵", "motor scooter"),
            new Entry("🏍", "motorcycle"),
            new Entry("🚨", "police light"),
            new Entry("🚔", "police car oncoming"),
            new Entry("🚍", "bus oncoming"),
            new Entry("🚘", "automobile oncoming"),
            new Entry("🚖", "taxi oncoming"),
            new Entry("🚡", "aerial tramway"),
            new Entry("🚠", "mountain cableway"),
            new Entry("🚟", "suspension railway"),
            new Entry("🚃", "railway car"),
            new Entry("🚋", "tram car"),
            new Entry("🚞", "mountain railway"),
            new Entry("🚝", "monorail"),
            new Entry("🚄", "high speed train"),
            new Entry("🚅", "bullet train"),
            new Entry("🚈", "light rail"),
            new Entry("🚂", "locomotive"),
            new Entry("🚆", "train"),
            new Entry("🚇", "metro subway"),
            new Entry("🚊", "tram"),
            new Entry("🚉", "station"),
            new Entry("✈", "airplane"),
            new Entry("🛫", "departure plane"),
            new Entry("🛬", "arrival plane"),
            new Entry("🛩", "small airplane"),
            new Entry("💺", "seat"),
            new Entry("🚀", "rocket launch"),
            new Entry("🛸", "ufo"),
            new Entry("🚁", "helicopter"),
            new Entry("🛶", "canoe"),
            new Entry("⛵", "sailboat"),
            new Entry("🚤", "speedboat"),
            new Entry("🛥", "motor boat"),
            new Entry("🛳", "passenger ship"),
            new Entry("⛴", "ferry"),
            new Entry("🚢", "ship"),
            new Entry("⚓", "anchor"),
            new Entry("⛽", "fuel pump gas"),
            new Entry("🚧", "construction"),
            new Entry("🚦", "traffic light vertical"),
            new Entry("🚥", "traffic light horizontal"),
            new Entry("🗺", "world map"),
            new Entry("🗿", "moai"),
            new Entry("🗽", "statue of liberty"),
            new Entry("🗼", "tokyo tower"),
            new Entry("🏰", "castle"),
            new Entry("🏯", "japanese castle"),
            new Entry("🏟", "stadium"),
            new Entry("🎡", "ferris wheel"),
            new Entry("🎢", "roller coaster"),
            new Entry("🎠", "carousel"),
            new Entry("⛲", "fountain"),
            new Entry("⛱", "umbrella beach"),
            new Entry("🏖", "beach umbrella"),
            new Entry("🏝", "desert island"),
            new Entry("🏜", "desert"),
            new Entry("🌋", "volcano"),
            new Entry("⛰", "mountain"),
            new Entry("🏔", "snow capped mountain"),
            new Entry("🗻", "mt fuji"),
            new Entry("🏕", "camping tent"),
            new Entry("⛺", "tent"),
            new Entry("🏠", "house"),
            new Entry("🏡", "house garden"),
            new Entry("🏘", "houses"),
            new Entry("🏚", "derelict house"),
            new Entry("🏗", "construction building"),
            new Entry("🏭", "factory"),
            new Entry("🏢", "office"),
            new Entry("🏬", "department store"),
            new Entry("🏣", "japanese post"),
            new Entry("🏤", "european post"),
            new Entry("🏥", "hospital"),
            new Entry("🏦", "bank"),
            new Entry("🏨", "hotel"),
            new Entry("🏪", "convenience store"),
            new Entry("🏫", "school"),
            new Entry("🏩", "love hotel"),
            new Entry("💒", "wedding"),
            new Entry("🏛", "classical building"),
            new Entry("⛪", "church"),
            new Entry("🕌", "mosque"),
            new Entry("🕍", "synagogue"),
            new Entry("🛕", "hindu temple"),
            new Entry("🌅", "sunrise"),
            new Entry("🌄", "sunrise mountain"),
            new Entry("🌠", "shooting star"),
            new Entry("🌌", "milky way galaxy"),
            new Entry("🌃", "starry night"),
            new Entry("🌆", "city dusk"),
            new Entry("🌇", "city sunset"),
            new Entry("🌉", "bridge night"),
            new Entry("🌁", "foggy"),
            new Entry("🌈", "rainbow"),
            new Entry("☀", "sun"),
            new Entry("🌞", "sun face"),
            new Entry("🌝", "full moon face"),
            new Entry("🌚", "new moon face"),
            new Entry("🌜", "last quarter moon face"),
            new Entry("🌛", "first quarter moon face"),
            new Entry("🌙", "crescent moon"),
            new Entry("🌎", "earth americas"),
            new Entry("🌍", "earth africa"),
            new Entry("🌏", "earth asia"),
            new Entry("⛅", "sun cloud"),
            new Entry("⛈", "cloud lightning rain"),
            new Entry("🌤", "sun small cloud"),
            new Entry("🌥", "sun large cloud"),
            new Entry("🌦", "sun rain"),
            new Entry("🌧", "cloud rain"),
            new Entry("🌨", "cloud snow"),
            new Entry("🌩", "cloud lightning"),
            new Entry("🌪", "tornado"),
            new Entry("🌫", "fog"),
            new Entry("🌬", "wind face"),
            new Entry("☔", "umbrella with rain"),
            new Entry("☂", "umbrella"),
            new Entry("❄", "snowflake"),
            new Entry("☃", "snowman"),
            new Entry("⛄", "snowman without snow"),
            new Entry("☄", "comet"),
            new Entry("🔥", "fire flame"),
            new Entry("💧", "droplet water"),
            new Entry("🌊", "wave water")
        ));

        BY_CATEGORY.put("objects", Arrays.asList(
            new Entry("⌚", "watch"),
            new Entry("📱", "phone mobile"),
            new Entry("📲", "phone arrow"),
            new Entry("💻", "laptop computer"),
            new Entry("⌨", "keyboard"),
            new Entry("🖥", "desktop"),
            new Entry("🖨", "printer"),
            new Entry("🖱", "mouse computer"),
            new Entry("🖲", "trackball"),
            new Entry("🕹", "joystick"),
            new Entry("🗜", "clamp"),
            new Entry("💽", "minidisc"),
            new Entry("💾", "floppy save"),
            new Entry("💿", "cd disc"),
            new Entry("📀", "dvd"),
            new Entry("📼", "videocassette"),
            new Entry("📷", "camera"),
            new Entry("📸", "camera flash"),
            new Entry("📹", "video camera"),
            new Entry("🎥", "movie camera"),
            new Entry("📽", "film projector"),
            new Entry("🎞", "film frames"),
            new Entry("📞", "telephone"),
            new Entry("☎", "phone classic"),
            new Entry("📟", "pager"),
            new Entry("📠", "fax"),
            new Entry("📺", "tv"),
            new Entry("📻", "radio"),
            new Entry("🎙", "studio microphone"),
            new Entry("🎚", "level slider"),
            new Entry("🎛", "control knobs"),
            new Entry("🧭", "compass"),
            new Entry("⏱", "stopwatch"),
            new Entry("⏲", "timer"),
            new Entry("⏰", "alarm clock"),
            new Entry("🕰", "mantelpiece clock"),
            new Entry("⌛", "hourglass"),
            new Entry("⏳", "hourglass flowing"),
            new Entry("📡", "satellite antenna"),
            new Entry("🔋", "battery"),
            new Entry("🔌", "electric plug"),
            new Entry("💡", "lightbulb idea"),
            new Entry("🔦", "flashlight"),
            new Entry("🕯", "candle"),
            new Entry("🪔", "diya lamp"),
            new Entry("🧯", "fire extinguisher"),
            new Entry("🛢", "oil drum"),
            new Entry("💸", "money wings"),
            new Entry("💵", "dollar"),
            new Entry("💴", "yen"),
            new Entry("💶", "euro"),
            new Entry("💷", "pound"),
            new Entry("💰", "money bag"),
            new Entry("💳", "credit card"),
            new Entry("💎", "gem diamond"),
            new Entry("⚖", "balance scale"),
            new Entry("🪜", "ladder"),
            new Entry("🧰", "toolbox"),
            new Entry("🪛", "screwdriver"),
            new Entry("🔧", "wrench"),
            new Entry("🔨", "hammer"),
            new Entry("⚒", "hammer pick"),
            new Entry("🛠", "tools"),
            new Entry("⛏", "pick"),
            new Entry("🪚", "saw"),
            new Entry("🔩", "nut bolt"),
            new Entry("⚙", "gear settings"),
            new Entry("🪤", "mouse trap"),
            new Entry("🧱", "brick"),
            new Entry("⛓", "chains"),
            new Entry("🧲", "magnet"),
            new Entry("🔫", "water pistol"),
            new Entry("💣", "bomb"),
            new Entry("🧨", "firecracker"),
            new Entry("🪓", "axe"),
            new Entry("🔪", "knife kitchen"),
            new Entry("🗡", "dagger"),
            new Entry("⚔", "crossed swords"),
            new Entry("🛡", "shield"),
            new Entry("🚬", "cigarette"),
            new Entry("⚰", "coffin"),
            new Entry("⚱", "urn"),
            new Entry("🏺", "amphora"),
            new Entry("🔮", "crystal ball"),
            new Entry("📿", "prayer beads"),
            new Entry("🧿", "nazar amulet"),
            new Entry("💈", "barber pole"),
            new Entry("⚗", "alembic"),
            new Entry("🔭", "telescope"),
            new Entry("🔬", "microscope"),
            new Entry("🕳", "hole"),
            new Entry("🩹", "adhesive bandage"),
            new Entry("🩺", "stethoscope"),
            new Entry("💊", "pill"),
            new Entry("💉", "syringe"),
            new Entry("🧬", "dna"),
            new Entry("🦠", "microbe virus"),
            new Entry("🧫", "petri dish"),
            new Entry("🧪", "test tube"),
            new Entry("🌡", "thermometer"),
            new Entry("🧹", "broom"),
            new Entry("🧺", "basket"),
            new Entry("🧻", "toilet paper"),
            new Entry("🚽", "toilet"),
            new Entry("🚰", "potable water"),
            new Entry("🚿", "shower"),
            new Entry("🛁", "bathtub"),
            new Entry("🛀", "person bath"),
            new Entry("🧼", "soap"),
            new Entry("🪥", "toothbrush"),
            new Entry("🪒", "razor"),
            new Entry("🧽", "sponge"),
            new Entry("🪣", "bucket"),
            new Entry("🧴", "lotion bottle"),
            new Entry("🛎", "bellhop bell"),
            new Entry("🔑", "key"),
            new Entry("🗝", "old key"),
            new Entry("🚪", "door"),
            new Entry("🪑", "chair"),
            new Entry("🛋", "couch lamp"),
            new Entry("🛏", "bed"),
            new Entry("🛌", "person bed"),
            new Entry("🧸", "teddy bear"),
            new Entry("🖼", "picture frame"),
            new Entry("🪞", "mirror"),
            new Entry("🪟", "window"),
            new Entry("🛍", "shopping bags"),
            new Entry("🛒", "shopping cart"),
            new Entry("🎁", "gift wrapped"),
            new Entry("🎈", "balloon"),
            new Entry("🎀", "ribbon"),
            new Entry("🎊", "confetti"),
            new Entry("🎉", "party popper celebrate"),
            new Entry("🎎", "japanese dolls"),
            new Entry("🎏", "carp streamer"),
            new Entry("🎐", "wind chime"),
            new Entry("🧧", "red envelope"),
            new Entry("✉", "envelope"),
            new Entry("📩", "envelope arrow"),
            new Entry("📨", "incoming envelope"),
            new Entry("📧", "email"),
            new Entry("💌", "love letter"),
            new Entry("📥", "inbox"),
            new Entry("📤", "outbox"),
            new Entry("📦", "package box"),
            new Entry("🏷", "label tag"),
            new Entry("📪", "closed mailbox"),
            new Entry("📫", "mailbox flag"),
            new Entry("📬", "open mailbox"),
            new Entry("📭", "open mailbox lowered"),
            new Entry("📮", "postbox"),
            new Entry("📯", "postal horn"),
            new Entry("📜", "scroll"),
            new Entry("📃", "page curl"),
            new Entry("📄", "page"),
            new Entry("📑", "bookmark tabs"),
            new Entry("📊", "bar chart"),
            new Entry("📈", "chart up"),
            new Entry("📉", "chart down"),
            new Entry("🗒", "spiral notepad"),
            new Entry("🗓", "spiral calendar"),
            new Entry("📆", "tear off calendar"),
            new Entry("📅", "calendar"),
            new Entry("📇", "card index"),
            new Entry("🗃", "card box"),
            new Entry("🗳", "ballot box"),
            new Entry("🗄", "file cabinet"),
            new Entry("📋", "clipboard"),
            new Entry("📁", "folder"),
            new Entry("📂", "open folder"),
            new Entry("🗂", "card index dividers"),
            new Entry("🗞", "rolled newspaper"),
            new Entry("📰", "newspaper"),
            new Entry("📓", "notebook"),
            new Entry("📔", "notebook decorative"),
            new Entry("📒", "ledger"),
            new Entry("📕", "closed book red"),
            new Entry("📗", "closed book green"),
            new Entry("📘", "closed book blue"),
            new Entry("📙", "closed book orange"),
            new Entry("📚", "books"),
            new Entry("📖", "open book"),
            new Entry("🔖", "bookmark"),
            new Entry("🧷", "safety pin"),
            new Entry("🔗", "link"),
            new Entry("📎", "paperclip"),
            new Entry("🖇", "linked paperclips"),
            new Entry("📐", "triangular ruler"),
            new Entry("📏", "straight ruler"),
            new Entry("🧮", "abacus"),
            new Entry("📌", "pushpin"),
            new Entry("📍", "round pushpin"),
            new Entry("✂", "scissors"),
            new Entry("🖊", "pen"),
            new Entry("🖋", "fountain pen"),
            new Entry("✒", "black nib"),
            new Entry("🖌", "paintbrush"),
            new Entry("🖍", "crayon"),
            new Entry("📝", "memo pencil"),
            new Entry("✏", "pencil"),
            new Entry("🔍", "magnifier left"),
            new Entry("🔎", "magnifier right"),
            new Entry("🔏", "locked pen"),
            new Entry("🔐", "locked key"),
            new Entry("🔒", "locked"),
            new Entry("🔓", "unlocked")
        ));

        BY_CATEGORY.put("symbols", Arrays.asList(
            new Entry("❤", "red heart love"),
            new Entry("🧡", "orange heart"),
            new Entry("💛", "yellow heart"),
            new Entry("💚", "green heart"),
            new Entry("💙", "blue heart"),
            new Entry("💜", "purple heart"),
            new Entry("🖤", "black heart"),
            new Entry("🤍", "white heart"),
            new Entry("🤎", "brown heart"),
            new Entry("💔", "broken heart"),
            new Entry("❣", "heart exclamation"),
            new Entry("💕", "two hearts"),
            new Entry("💞", "revolving hearts"),
            new Entry("💓", "beating heart"),
            new Entry("💗", "growing heart"),
            new Entry("💖", "sparkling heart"),
            new Entry("💘", "heart arrow"),
            new Entry("💝", "heart ribbon"),
            new Entry("💟", "heart decoration"),
            new Entry("☮", "peace symbol"),
            new Entry("✝", "latin cross"),
            new Entry("☪", "star and crescent"),
            new Entry("🕉", "om"),
            new Entry("☸", "wheel of dharma"),
            new Entry("✡", "star of david"),
            new Entry("🔯", "six pointed star"),
            new Entry("🕎", "menorah"),
            new Entry("☯", "yin yang"),
            new Entry("☦", "orthodox cross"),
            new Entry("🛐", "place of worship"),
            new Entry("⛎", "ophiuchus"),
            new Entry("♈", "aries"),
            new Entry("♉", "taurus"),
            new Entry("♊", "gemini"),
            new Entry("♋", "cancer"),
            new Entry("♌", "leo"),
            new Entry("♍", "virgo"),
            new Entry("♎", "libra"),
            new Entry("♏", "scorpio"),
            new Entry("♐", "sagittarius"),
            new Entry("♑", "capricorn"),
            new Entry("♒", "aquarius"),
            new Entry("♓", "pisces"),
            new Entry("🆔", "id button"),
            new Entry("⚛", "atom"),
            new Entry("🉑", "accept"),
            new Entry("☢", "radioactive"),
            new Entry("☣", "biohazard"),
            new Entry("📴", "phone off"),
            new Entry("📳", "vibration mode"),
            new Entry("🈶", "japanese not free"),
            new Entry("🈚", "japanese free"),
            new Entry("🈸", "japanese application"),
            new Entry("🈺", "japanese open"),
            new Entry("🈷", "japanese monthly"),
            new Entry("✴", "eight pointed star"),
            new Entry("🆚", "vs"),
            new Entry("💮", "white flower"),
            new Entry("🉐", "bargain"),
            new Entry("㊙", "secret"),
            new Entry("㊗", "congratulations"),
            new Entry("🈴", "japanese passing"),
            new Entry("🈵", "japanese full"),
            new Entry("🈹", "japanese discount"),
            new Entry("🈲", "japanese prohibited"),
            new Entry("🅰", "a button"),
            new Entry("🅱", "b button"),
            new Entry("🆎", "ab button"),
            new Entry("🆑", "cl button"),
            new Entry("🅾", "o button"),
            new Entry("🆘", "sos"),
            new Entry("❌", "cross mark"),
            new Entry("⭕", "hollow red circle"),
            new Entry("🛑", "stop sign"),
            new Entry("⛔", "no entry"),
            new Entry("📛", "name badge"),
            new Entry("🚫", "prohibited"),
            new Entry("💯", "100 hundred"),
            new Entry("💢", "anger"),
            new Entry("♨", "hot springs"),
            new Entry("🚷", "no pedestrians"),
            new Entry("🚯", "no littering"),
            new Entry("🚳", "no bicycles"),
            new Entry("🚱", "non potable water"),
            new Entry("🔞", "no one under eighteen"),
            new Entry("📵", "no phone"),
            new Entry("🚭", "no smoking"),
            new Entry("❗", "exclamation"),
            new Entry("❕", "white exclamation"),
            new Entry("❓", "question mark"),
            new Entry("❔", "white question"),
            new Entry("‼", "double exclamation"),
            new Entry("⁉", "interrobang"),
            new Entry("🔅", "low brightness"),
            new Entry("🔆", "high brightness"),
            new Entry("〽", "part alternation"),
            new Entry("⚠", "warning"),
            new Entry("🚸", "children crossing"),
            new Entry("🔱", "trident"),
            new Entry("⚜", "fleur de lis"),
            new Entry("🔰", "japanese symbol for beginner"),
            new Entry("♻", "recycle"),
            new Entry("✅", "check mark green"),
            new Entry("🈯", "japanese reserved"),
            new Entry("💹", "chart yen"),
            new Entry("❇", "sparkle"),
            new Entry("✳", "eight spoked asterisk"),
            new Entry("❎", "cross button"),
            new Entry("🌐", "globe meridians"),
            new Entry("💠", "diamond dot"),
            new Entry("Ⓜ", "circled m"),
            new Entry("🌀", "cyclone"),
            new Entry("💤", "zzz sleep"),
            new Entry("🏧", "atm"),
            new Entry("🚾", "wc"),
            new Entry("♿", "wheelchair"),
            new Entry("🅿", "p button parking"),
            new Entry("🛗", "elevator"),
            new Entry("🈳", "japanese vacancy"),
            new Entry("🈂", "japanese service"),
            new Entry("🛂", "passport control"),
            new Entry("🛃", "customs"),
            new Entry("🛄", "baggage claim"),
            new Entry("🛅", "left luggage"),
            new Entry("🚹", "men room"),
            new Entry("🚺", "women room"),
            new Entry("🚼", "baby symbol"),
            new Entry("🚻", "restroom"),
            new Entry("🚮", "litter"),
            new Entry("🎦", "cinema"),
            new Entry("📶", "antenna bars signal"),
            new Entry("🈁", "japanese here"),
            new Entry("🔣", "input symbols"),
            new Entry("ℹ", "information"),
            new Entry("🔤", "input latin letters"),
            new Entry("🔡", "lowercase"),
            new Entry("🔠", "uppercase"),
            new Entry("🆖", "ng"),
            new Entry("🆗", "ok button"),
            new Entry("🆙", "up button"),
            new Entry("🆒", "cool button"),
            new Entry("🆕", "new button"),
            new Entry("🆓", "free button"),
            new Entry("0️⃣", "zero"),
            new Entry("1️⃣", "one"),
            new Entry("2️⃣", "two"),
            new Entry("3️⃣", "three"),
            new Entry("4️⃣", "four"),
            new Entry("5️⃣", "five"),
            new Entry("6️⃣", "six"),
            new Entry("7️⃣", "seven"),
            new Entry("8️⃣", "eight"),
            new Entry("9️⃣", "nine"),
            new Entry("🔟", "ten"),
            new Entry("🔢", "input numbers"),
            new Entry("#️⃣", "hash"),
            new Entry("*️⃣", "asterisk"),
            new Entry("⏏", "eject"),
            new Entry("▶", "play"),
            new Entry("⏸", "pause"),
            new Entry("⏯", "play pause"),
            new Entry("⏹", "stop button"),
            new Entry("⏺", "record"),
            new Entry("⏭", "next track"),
            new Entry("⏮", "previous track"),
            new Entry("⏩", "fast forward"),
            new Entry("⏪", "fast reverse"),
            new Entry("⏫", "fast up"),
            new Entry("⏬", "fast down"),
            new Entry("◀", "reverse"),
            new Entry("🔼", "upwards button"),
            new Entry("🔽", "downwards button"),
            new Entry("➡", "right arrow"),
            new Entry("⬅", "left arrow"),
            new Entry("⬆", "up arrow"),
            new Entry("⬇", "down arrow"),
            new Entry("↗", "up right arrow"),
            new Entry("↘", "down right arrow"),
            new Entry("↙", "down left arrow"),
            new Entry("↖", "up left arrow"),
            new Entry("↕", "up down arrow"),
            new Entry("↔", "left right arrow"),
            new Entry("↪", "right hook arrow"),
            new Entry("↩", "left hook arrow"),
            new Entry("⤴", "right curving up"),
            new Entry("⤵", "right curving down"),
            new Entry("🔀", "shuffle"),
            new Entry("🔁", "repeat"),
            new Entry("🔂", "repeat single"),
            new Entry("🔄", "counterclockwise"),
            new Entry("🔃", "clockwise vertical")
        ));

        BY_CATEGORY.put("flags", Arrays.asList(
            new Entry("🏳", "white flag"),
            new Entry("🏴", "black flag"),
            new Entry("🏁", "checkered finish"),
            new Entry("🚩", "triangular flag"),
            new Entry("🏳️‍🌈", "rainbow pride"),
            new Entry("🏳️‍⚧️", "transgender flag"),
            new Entry("🏴‍☠️", "pirate skull"),
            new Entry("🇺🇸", "united states usa flag"),
            new Entry("🇬🇧", "united kingdom uk flag"),
            new Entry("🇨🇦", "canada flag"),
            new Entry("🇲🇽", "mexico flag"),
            new Entry("🇧🇷", "brazil flag"),
            new Entry("🇦🇷", "argentina flag"),
            new Entry("🇩🇪", "germany flag"),
            new Entry("🇫🇷", "france flag"),
            new Entry("🇮🇹", "italy flag"),
            new Entry("🇪🇸", "spain flag"),
            new Entry("🇵🇹", "portugal flag"),
            new Entry("🇳🇱", "netherlands flag"),
            new Entry("🇧🇪", "belgium flag"),
            new Entry("🇨🇭", "switzerland flag"),
            new Entry("🇦🇹", "austria flag"),
            new Entry("🇸🇪", "sweden flag"),
            new Entry("🇳🇴", "norway flag"),
            new Entry("🇩🇰", "denmark flag"),
            new Entry("🇫🇮", "finland flag"),
            new Entry("🇮🇪", "ireland flag"),
            new Entry("🇮🇸", "iceland flag"),
            new Entry("🇵🇱", "poland flag"),
            new Entry("🇨🇿", "czech flag"),
            new Entry("🇸🇰", "slovakia flag"),
            new Entry("🇭🇺", "hungary flag"),
            new Entry("🇷🇴", "romania flag"),
            new Entry("🇧🇬", "bulgaria flag"),
            new Entry("🇬🇷", "greece flag"),
            new Entry("🇹🇷", "turkey flag"),
            new Entry("🇷🇺", "russia flag"),
            new Entry("🇺🇦", "ukraine flag"),
            new Entry("🇮🇳", "india flag"),
            new Entry("🇵🇰", "pakistan flag"),
            new Entry("🇧🇩", "bangladesh flag"),
            new Entry("🇱🇰", "sri lanka flag"),
            new Entry("🇳🇵", "nepal flag"),
            new Entry("🇨🇳", "china flag"),
            new Entry("🇯🇵", "japan flag"),
            new Entry("🇰🇷", "south korea flag"),
            new Entry("🇰🇵", "north korea flag"),
            new Entry("🇹🇼", "taiwan flag"),
            new Entry("🇭🇰", "hong kong flag"),
            new Entry("🇸🇬", "singapore flag"),
            new Entry("🇲🇾", "malaysia flag"),
            new Entry("🇮🇩", "indonesia flag"),
            new Entry("🇵🇭", "philippines flag"),
            new Entry("🇹🇭", "thailand flag"),
            new Entry("🇻🇳", "vietnam flag"),
            new Entry("🇰🇭", "cambodia flag"),
            new Entry("🇲🇲", "myanmar flag"),
            new Entry("🇦🇺", "australia flag"),
            new Entry("🇳🇿", "new zealand flag"),
            new Entry("🇿🇦", "south africa flag"),
            new Entry("🇪🇬", "egypt flag"),
            new Entry("🇲🇦", "morocco flag"),
            new Entry("🇩🇿", "algeria flag"),
            new Entry("🇸🇦", "saudi arabia flag"),
            new Entry("🇦🇪", "uae emirates flag"),
            new Entry("🇮🇷", "iran flag"),
            new Entry("🇮🇶", "iraq flag"),
            new Entry("🇮🇱", "israel flag"),
            new Entry("🇯🇴", "jordan flag"),
            new Entry("🇱🇧", "lebanon flag"),
            new Entry("🇸🇾", "syria flag"),
            new Entry("🇶🇦", "qatar flag"),
            new Entry("🇰🇼", "kuwait flag"),
            new Entry("🇴🇲", "oman flag"),
            new Entry("🇾🇪", "yemen flag"),
            new Entry("🇦🇫", "afghanistan flag"),
            new Entry("🇰🇪", "kenya flag"),
            new Entry("🇳🇬", "nigeria flag"),
            new Entry("🇬🇭", "ghana flag"),
            new Entry("🇪🇹", "ethiopia flag")
        ));
    }
}
